[tool.poetry]
name = "adeptus-administratum"
version = "0.1.0"
description = ""
authors = ["IJMadalenA"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.1"
django-environ = "^0.10.0"
environ = "^1.0"
poetry = "^1.5.0"
binance-connector = "^3.0.0"
python-binance = "^1.0.17"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
