# Generated by Django 4.2.1 on 2023-08-01 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("BinanceAPI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaxNumberOrdersFilter",
            fields=[
                (
                    "basefilter_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="BinanceAPI.basefilter",
                    ),
                ),
                (
                    "max_num_orders",
                    models.IntegerField(
                        blank=True,
                        editable=False,
                        help_text="Máximo número de órdenes",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Filtro de Máximo Número de Órdenes",
                "verbose_name_plural": "Filtros de Máximo Número de Órdenes",
                "db_table": "max_number_orders_filter",
            },
            bases=("BinanceAPI.basefilter",),
        ),
    ]
