# Generated by Django 4.2.1 on 2023-07-15 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("BinanceAPI", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PriceHistory",
        ),
        migrations.RemoveField(
            model_name="candlestick",
            name="asset",
        ),
        migrations.AddField(
            model_name="candlestick",
            name="symbol",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Símbolo del par de trading",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candlesticks",
                to="BinanceAPI.symbol",
                verbose_name="Símbolo del par de trading",
            ),
        ),
        migrations.AddField(
            model_name="candlestick",
            name="time_frame",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1s", "1s"),
                    ("1m", "1m"),
                    ("3m", "3m"),
                    ("5m", "5m"),
                    ("15m", "15m"),
                    ("30m", "30m"),
                    ("1h", "1h"),
                    ("2h", "2h"),
                    ("4h", "4h"),
                    ("6h", "6h"),
                    ("8h", "8h"),
                    ("12h", "12h"),
                    ("1d", "1d"),
                    ("3d", "3d"),
                    ("5d", "5d"),
                    ("1w", "1w"),
                    ("2w", "2w"),
                    ("3w", "3w"),
                    ("1M", "1M"),
                    ("3M", "3M"),
                    ("6M", "6M"),
                    ("1y", "1y"),
                ],
                editable=False,
                help_text="Marco de tiempo de la vela",
                max_length=3,
                null=True,
                verbose_name="Marco de tiempo de la vela",
            ),
        ),
    ]
