# Generated by Django 4.2.1 on 2023-07-15 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("BinanceAPI", "0002_delete_pricehistory_remove_candlestick_asset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha y hora de actualización"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de creación"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Precio actual",
                        max_digits=20,
                    ),
                ),
                (
                    "price_change",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Cambio de precio en 24 horas",
                        max_digits=20,
                    ),
                ),
                (
                    "price_change_percent",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Porcentaje de cambio de precio en 24 horas",
                        max_digits=20,
                    ),
                ),
                (
                    "weighted_avg_price",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Precio promedio ponderado",
                        max_digits=20,
                    ),
                ),
                (
                    "prev_close_price",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Precio de cierre anterior",
                        max_digits=20,
                    ),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Último precio",
                        max_digits=20,
                    ),
                ),
                (
                    "bid_price",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Precio de oferta",
                        max_digits=20,
                    ),
                ),
                (
                    "ask_price",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Precio de demanda",
                        max_digits=20,
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Precio de apertura",
                        max_digits=20,
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Precio máximo",
                        max_digits=20,
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Precio mínimo",
                        max_digits=20,
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Volumen",
                        max_digits=20,
                    ),
                ),
                (
                    "open_time",
                    models.IntegerField(
                        editable=False, help_text="Marca de tiempo de apertura"
                    ),
                ),
                (
                    "close_time",
                    models.IntegerField(
                        editable=False, help_text="Marca de tiempo de cierre"
                    ),
                ),
                (
                    "first_trade_id",
                    models.IntegerField(
                        editable=False, help_text="ID de la primera operación"
                    ),
                ),
                (
                    "last_trade_id",
                    models.IntegerField(
                        editable=False, help_text="ID de la última operación"
                    ),
                ),
                (
                    "trade_count",
                    models.IntegerField(
                        editable=False, help_text="Número de operaciones"
                    ),
                ),
                (
                    "maker_commission",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Comisión de maker",
                        max_digits=20,
                    ),
                ),
                (
                    "taker_commission",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Comisión de taker",
                        max_digits=20,
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        editable=False,
                        help_text="Par de trading",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticker",
                        related_query_name="ticker",
                        to="BinanceAPI.symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticker",
                "verbose_name_plural": "Tickers",
            },
        ),
    ]
