# Generated by Django 4.2.1 on 2023-07-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BinanceAPI", "0002_withdrawal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha y hora de actualización"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de creación"
                    ),
                ),
                (
                    "trade_id",
                    models.CharField(
                        editable=False,
                        help_text="ID de la operación",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "asset",
                    models.CharField(
                        editable=False, help_text="Símbolo de trading", max_length=20
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        editable=False,
                        help_text="Lado de la operación (compra/venta)",
                        max_length=4,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Precio de la operación",
                        max_digits=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Cantidad de la operación",
                        max_digits=20,
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="Comisión de la operación",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        editable=False, help_text="Fecha y hora de la operación"
                    ),
                ),
                (
                    "is_maker",
                    models.BooleanField(
                        editable=False,
                        help_text="Indica si la operación fue creada por el maker",
                    ),
                ),
                (
                    "is_buyer",
                    models.BooleanField(
                        editable=False, help_text="Indica si el usuario es el comprador"
                    ),
                ),
                (
                    "commission_asset",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Símbolo de la comisión",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="Monto de la comisión",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="Tasa de comisión",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "buyer_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="Comisión del comprador",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "seller_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="Comisión del vendedor",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "trade_time",
                    models.BigIntegerField(
                        editable=False,
                        help_text="Tiempo de la operación en milisegundos",
                    ),
                ),
                (
                    "buyer_is_maker",
                    models.BooleanField(
                        editable=False, help_text="Indica si el comprador fue el maker"
                    ),
                ),
                (
                    "ignore",
                    models.BooleanField(
                        editable=False,
                        help_text="Indica si la operación debe ignorarse",
                    ),
                ),
            ],
            options={
                "verbose_name": "trade",
                "verbose_name_plural": "trades",
            },
        ),
        migrations.CreateModel(
            name="TradeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha y hora de actualización"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de creación"
                    ),
                ),
                (
                    "asset",
                    models.CharField(
                        editable=False,
                        help_text="El símbolo del par de trading.",
                        max_length=50,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        editable=False, help_text="La marca de tiempo de la operación."
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="El precio al que se realizó la operación.",
                        max_digits=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="La cantidad negociada en la operación.",
                        max_digits=20,
                    ),
                ),
                (
                    "is_buyer_maker",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        help_text="Indica si el comprador es el creador de la orden.",
                    ),
                ),
                (
                    "is_best_match",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        help_text="Indica si esta operación es el último precio negociado del par.",
                    ),
                ),
                (
                    "is_ignored",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        help_text="Indica si esta operación es ignorada en el historial.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade History",
                "verbose_name_plural": "Trade Histories",
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha y hora de actualización"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de creación"
                    ),
                ),
                (
                    "asset",
                    models.CharField(
                        choices=[("BTC", "Bitcoin"), ("ETH", "Ethereum")],
                        help_text="Activo de la cartera",
                        max_length=10,
                    ),
                ),
                (
                    "free",
                    models.DecimalField(
                        decimal_places=10, help_text="Saldo disponible", max_digits=20
                    ),
                ),
                (
                    "locked",
                    models.DecimalField(
                        decimal_places=10, help_text="Saldo bloqueado", max_digits=20
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Saldo total (disponible + bloqueado)",
                        max_digits=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "wallet",
                "verbose_name_plural": "wallets",
            },
        ),
    ]
