# Generated by Django 4.2.1 on 2023-07-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("BinanceAPI", "0003_trade_tradehistory_wallet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha y hora de actualización"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de creación"
                    ),
                ),
                (
                    "asset",
                    models.CharField(
                        editable=False,
                        help_text="Símbolo del activo",
                        max_length=10,
                        verbose_name="symbolo del activo",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="ID de la orden",
                        max_length=50,
                        unique=True,
                        verbose_name="ID de la orden",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Precio de la orden",
                        max_digits=20,
                        verbose_name="Precio de la orden",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Cantidad de activos",
                        max_digits=20,
                        verbose_name="Cantidad de activos",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        editable=False,
                        help_text="Lado de la orden",
                        max_length=4,
                        verbose_name="Laso de la orden",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("FILLED", "Filled"),
                            ("CANCELED", "Canceled"),
                        ],
                        editable=False,
                        help_text="Estado de la orden",
                        max_length=8,
                        verbose_name="Estado de la orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="OrderBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha y hora de actualización"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de creación"
                    ),
                ),
                (
                    "last_update_id",
                    models.BigIntegerField(
                        blank=True,
                        editable=False,
                        help_text="ID de última actualización del libro de órdenes",
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de la actualización del libro de órdenes",
                        null=True,
                    ),
                ),
                (
                    "asks",
                    models.JSONField(
                        blank=True,
                        editable=False,
                        help_text="La lista de órdenes de venta (asks) del libro de órdenes.",
                        null=True,
                    ),
                ),
                (
                    "bids",
                    models.JSONField(
                        blank=True,
                        editable=False,
                        help_text="La lista de órdenes de compra (bids) del libro de órdenes.",
                        null=True,
                    ),
                ),
                (
                    "ask_total_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="El volumen total de las órdenes de venta.",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "bid_total_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="El volumen total de las órdenes de compra.",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "spread",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="La diferencia entre el precio más alto de las órdenes de compra y el precio más bajo de las órdenes de venta.",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "liquidity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="La liquidez del par de trading.",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="La profundidad del libro de órdenes.",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Símbolo del par de trading",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_books",
                        to="BinanceAPI.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Book",
                "verbose_name_plural": "Order Books",
            },
        ),
    ]
