# Generated by Django 4.2.1 on 2023-07-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("BinanceAPI", "0004_order_orderbook"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candlestick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha y hora de actualización"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de creación"
                    ),
                ),
                (
                    "time_frame",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1s", "1s"),
                            ("1m", "1m"),
                            ("3m", "3m"),
                            ("5m", "5m"),
                            ("15m", "15m"),
                            ("30m", "30m"),
                            ("1h", "1h"),
                            ("2h", "2h"),
                            ("4h", "4h"),
                            ("6h", "6h"),
                            ("8h", "8h"),
                            ("12h", "12h"),
                            ("1d", "1d"),
                            ("3d", "3d"),
                            ("5d", "5d"),
                            ("1w", "1w"),
                            ("2w", "2w"),
                            ("3w", "3w"),
                            ("1M", "1M"),
                            ("3M", "3M"),
                            ("6M", "6M"),
                            ("1y", "1y"),
                        ],
                        editable=False,
                        help_text="Marco de tiempo de la vela",
                        max_length=3,
                        null=True,
                        verbose_name="Marco de tiempo de la vela",
                    ),
                ),
                (
                    "open_time",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Fecha y hora de apertura de la vela",
                        null=True,
                        verbose_name="Fecha y hora de apertura de la vela",
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="Precio de apertura de la vela",
                        max_digits=20,
                        null=True,
                        verbose_name="Precio de apertura de la vela",
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="Precio más alto de la vela",
                        max_digits=20,
                        null=True,
                        verbose_name="Precio más alto de la vela",
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="Precio más bajo de la vela",
                        max_digits=20,
                        null=True,
                        verbose_name="Precio más bajo de la vela",
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="Precio de cierre de la vela",
                        max_digits=20,
                        null=True,
                        verbose_name="Precio de cierre de la vela",
                    ),
                ),
                (
                    "adj_close_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="Precio de cierre ajustado de la vela",
                        max_digits=20,
                        null=True,
                        verbose_name="Precio de cierre ajustado de la vela",
                    ),
                ),
                (
                    "close_time",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Fecha y hora de cierre de la vela",
                        null=True,
                        verbose_name="Fecha y hora de cierre de la vela",
                    ),
                ),
                (
                    "quote_asset_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="Volumen de trading en la vela",
                        max_digits=30,
                        null=True,
                        verbose_name="Volumen de trading en la vela",
                    ),
                ),
                (
                    "number_of_trades",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="Número de trades en la vela",
                        max_digits=30,
                        null=True,
                        verbose_name="Número de trades en la vela",
                    ),
                ),
                (
                    "taker_buy_quote_asset_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="Volumen de trading de la vela",
                        max_digits=30,
                        null=True,
                        verbose_name="Volumen de trading de la vela",
                    ),
                ),
                (
                    "taker_buy_base_asset_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="Volumen de trading de la vela",
                        max_digits=30,
                        null=True,
                        verbose_name="Volumen de trading de la vela",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        editable=False,
                        help_text="Volumen de trading de la vela",
                        max_digits=30,
                        null=True,
                        verbose_name="Volumen de trading de la vela",
                    ),
                ),
                (
                    "market_cap",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Capitalización de mercado",
                        max_digits=20,
                        verbose_name="Capitalización de mercado",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Símbolo del par de trading",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candlesticks",
                        to="BinanceAPI.symbol",
                        verbose_name="Símbolo del par de trading",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vela",
                "verbose_name_plural": "Velas",
                "ordering": ["symbol", "open_time"],
            },
        ),
        migrations.CreateModel(
            name="AvgPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha y hora de actualización"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de creación"
                    ),
                ),
                (
                    "mins",
                    models.IntegerField(
                        editable=False,
                        help_text="Minutos de los que se calcula el promedio",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=10,
                        editable=False,
                        help_text="Precio promedio",
                        max_digits=20,
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        editable=False,
                        help_text="Activo",
                        max_length=10,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="BinanceAPI.symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio promedio",
                "verbose_name_plural": "Precios promedios",
                "ordering": ["symbol", "mins"],
            },
        ),
        migrations.AddConstraint(
            model_name="avgprice",
            constraint=models.UniqueConstraint(
                fields=("symbol", "mins"), name="unique_symbol_mins"
            ),
        ),
    ]
