version: '3.9'

services:
  orikan:
    container_name: Orikan-Container
    hostname: orikan
    build:
      context: ../../orikan/
      dockerfile: tesseract-vault/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "python manage.py test" ]
      interval: 30s
      timeout: 70s
      retries: 3
    volumes:
      - "../../orikan/:/home/orikan/"
      - "static_volume:/home/orikan/static"
      - "media_volume:/home/orikan/media"
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      solemnace_galleries:
        condition: service_healthy

  solemnace_galleries:
    container_name: Solemnace_Galleries
    hostname: solemnace_galleries
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "psql pg_isready", "-U", "trazyn_the_infinite", "-d", "solemnace-galleries"]
      interval: 10s
      timeout: 7s
      retries: 5
      start_period: 5s
    stdin_open: true
    tty: true
    env_file:
      - ../.env
    expose:
      - '5432'
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    container_name: Redis
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

volumes:
  media_volume:
  static_volume:
  postgres_data:
  airflow-logs:
